language: csharp
solution: Beer.NET.sln
install:
  - nuget restore Beer.NET.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Beer.NET.sln
  - mono ./testrunner/NUnit.Runners/tools/nunit-console.exe ./Beer.NET.Tests/bin/Release/Beer.NET.Tests.dll
