using NUnit.Framework;

namespace DerAtrox.BeerNET.Tests {
	[TestFixture]
	public class BeerTest {
		[Test]
		public void TestSerialize() {
			string serialized = Beer.SerializeBeer("qpalym._#ä");
			Assert.AreEqual(serialized, "BEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEER-BEER∫_#ä");
		}

		[Test]
		public void TestDeserialize() {
			string deserialized = Beer.DeserializeBeer("BEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEERBEER∫BEER-BEER∫_#ä");
			Assert.AreEqual(deserialized, "qpalym._#ä");
		}

		[Test]
		public void TestSerializeDeserialize() {
			Assert.AreEqual(Beer.DeserializeBeer(Beer.SerializeBeer("qpalym._#ä")), "qpalym._#ä");
		}
	}
}